### ISSUE TITLE
 Intl.DurationFormat empty response 

### ISSUE THREAD

**Issue by 3052** [formatjs/formatjs#4671]
its advertised here:

https://formatjs.github.io/docs/polyfills/intl-durationformat

but not available:

~~~js
/*
 * Polyfill service v3.111.0
 * For detailed credits and licence information see https://github.com/fastly/polyfill-service/.
 * 
 * Features requested: Intl.DurationFormat
 * 
 * 
 * These features were not recognised:
 * - Intl.DurationFormat
*/

/* No polyfills needed for current settings and browser */
~~~

https://polyfill-fastly.io/v3/polyfill.js?features=Intl.DurationFormat

I am on Firefox so I should be getting a polyfill:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DurationFormat#browser_compatibility

**Comment by longlho** [comment]
I've updated the docs. `DurationFormat` is not available on polyfill services

**Comment by 3052** [comment]
@longlho your comment doesn't address my issue at all - everything I said in the original post is still true

**Comment by longlho** [comment]
You have to use the other method to polyfill manually https://formatjs.github.io/docs/polyfills/intl-durationformat#simple

**Comment by 3052** [comment]
again, nothing you have said so far changes the fact that everything I have said so far is still true. this page still exists:

https://formatjs.github.io/docs/polyfills/intl-durationformat

it still contains this:

```
<script src="https://polyfill-fastly.io/v3/polyfill.min.js?features=Intl.DurationFormat"></script>
```

and that file is still empty - I dont see how you could possibly consider this a solved issue, as anyone visiting that page is still going to be confused/mislead

**Comment by longlho** [comment]
I just deployed a new version to remove that block
